from django.urls import path

from . import views

urlpatterns = [
    path('', views.dashboard, name='administrador'),
    path('productos/', views.productos_lista, name='panel_productos'),
    path('productos/nuevo/', views.producto_nuevo, name='panel_producto_nuevo'),
    path('productos/editar/<int:pk>/', views.producto_editar, name='panel_producto_editar'),
    path('productos/eliminar/<int:pk>/', views.producto_eliminar, name='panel_producto_eliminar'),
    path('usuarios/', views.usuarios_lista, name='panel_usuarios'),
    path('usuarios/nuevo/', views.usuario_nuevo, name='panel_usuario_nuevo'),
    path('usuarios/editar/<int:pk>/', views.usuario_editar, name='panel_usuario_editar'),
    path('usuarios/eliminar/<int:pk>/', views.usuario_eliminar, name='panel_usuario_eliminar'),
    path('marcas/', views.marcas_lista, name='panel_marcas'),
    path('marcas/nueva/', views.marca_form, name='panel_marca_nueva'),
    path('marcas/editar/<int:pk>/', views.marca_form, name='panel_marca_editar'),
    path('marcas/eliminar/<int:pk>/', views.marca_eliminar, name='panel_marca_eliminar'),
    path('colores/', views.colores_lista, name='panel_colores'),
    path('colores/nuevo/', views.color_form, name='panel_color_nuevo'),
    path('colores/editar/<int:pk>/', views.color_form, name='panel_color_editar'),
    path('colores/eliminar/<int:pk>/', views.color_eliminar, name='panel_color_eliminar'),
    path('categorias/', views.categorias_lista, name='panel_categorias'),
    path('categorias/nueva/', views.categoria_form, name='panel_categoria_nueva'),
    path('categorias/editar/<int:pk>/', views.categoria_form, name='panel_categoria_editar'),
    path('categorias/eliminar/<int:pk>/', views.categoria_eliminar, name='panel_categoria_eliminar'),
    path('generos/', views.generos_lista, name='panel_generos'),
    path('generos/nuevo/', views.genero_form, name='panel_genero_nuevo'),
    path('generos/editar/<int:pk>/', views.genero_form, name='panel_genero_editar'),
    path('generos/eliminar/<int:pk>/', views.genero_eliminar, name='panel_genero_eliminar'),
    path('tipos-cierre/', views.tipos_cierre_lista, name='panel_tipos_cierre'),
    path('tipos-cierre/nuevo/', views.tipo_cierre_form, name='panel_tipo_cierre_nuevo'),
    path('tipos-cierre/editar/<int:pk>/', views.tipo_cierre_form, name='panel_tipo_cierre_editar'),
    path('tipos-cierre/eliminar/<int:pk>/', views.tipo_cierre_eliminar, name='panel_tipo_cierre_eliminar'),
    path('productos/exportar-pdf/', views.productos_lista_pdf, name='panel_productos_pdf'),
    path('ventas/', views.ventas_lista, name='panel_ventas'),
    path('ventas/nueva/', views.venta_nuevo, name='panel_venta_nueva'),
    path('ventas/editar/<int:pk>/', views.venta_editar, name='panel_venta_editar'),
    path('ventas/eliminar/<int:pk>/', views.venta_eliminar, name='panel_venta_eliminar'),
    path('ventas/entregar/<int:pk>/', views.venta_entregar, name='panel_venta_entregar'),
    path('ventas/<int:pk>/', views.venta_ver, name='panel_venta_ver'),
    path('pagos/', views.pagos_lista, name='panel_pagos'),
    path('pagos/nuevo/', views.pago_nuevo, name='panel_pago_nuevo'),
    path('pagos/editar/<int:pk>/', views.pago_editar, name='panel_pago_editar'),
    path('pagos/eliminar/<int:pk>/', views.pago_eliminar, name='panel_pago_eliminar'),
    path('personalizacion/', views.personalizacion_lista, name='panel_personalizacion'),
    path('personalizacion/editar/<int:pk>/', views.personalizacion_editar, name='panel_personalizacion_editar'),
    path('personalizacion/eliminar/<int:pk>/', views.personalizacion_eliminar, name='panel_personalizacion_eliminar'),
    path('personalizacion/<int:pk>/', views.personalizacion_ver, name='panel_personalizacion_ver'),
]
