# Generated by Django 6.0.3 on 2026-03-17 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_categoria', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
        migrations.CreateModel(
            name='colores',
            fields=[
                ('id_color', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_color', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'colores',
            },
        ),
        migrations.CreateModel(
            name='genero',
            fields=[
                ('id_genero', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_genero', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'generos',
            },
        ),
        migrations.CreateModel(
            name='marcas',
            fields=[
                ('id_marca', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_marca', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_rol', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'roles',
            },
        ),
        migrations.CreateModel(
            name='tipos_cierres',
            fields=[
                ('id_tipo_cierre', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_cierre', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'tipos_cierres',
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('talla', models.CharField(max_length=20)),
                ('estado', models.CharField(max_length=20)),
                ('stock_producto', models.IntegerField()),
                ('descripcion', models.TextField()),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.CASCADE, to='tienda.categoria')),
                ('id_color', models.ForeignKey(db_column='id_color', on_delete=django.db.models.deletion.CASCADE, to='tienda.colores')),
                ('id_genero', models.ForeignKey(db_column='id_genero', on_delete=django.db.models.deletion.CASCADE, to='tienda.genero')),
                ('id_marca', models.ForeignKey(db_column='id_marca', on_delete=django.db.models.deletion.CASCADE, to='tienda.marcas')),
                ('id_tipo_cierre', models.ForeignKey(db_column='id_tipo_cierre', on_delete=django.db.models.deletion.CASCADE, to='tienda.tipos_cierres')),
            ],
            options={
                'db_table': 'productos',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('primer_nombre', models.CharField(max_length=50)),
                ('segundo_nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=50)),
                ('segundo_apellido', models.CharField(max_length=50)),
                ('direccion', models.CharField(max_length=100)),
                ('contacto', models.CharField(max_length=20)),
                ('gmail', models.EmailField(max_length=100)),
                ('clave', models.CharField(max_length=100)),
                ('id_rol', models.ForeignKey(db_column='id_rol', on_delete=django.db.models.deletion.CASCADE, to='tienda.rol')),
            ],
            options={
                'db_table': 'usuarios',
            },
        ),
    ]
