# Generated by Django 6.0.3 on 2026-04-02 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0007_venta_fecha_solo_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, db_column='imagen', null=True, upload_to='productos/'),
        ),
        migrations.CreateModel(
            name='Valoracion',
            fields=[
                ('id_valoracion', models.AutoField(primary_key=True, serialize=False)),
                ('valor_puntuacion', models.IntegerField()),
                ('fecha_puntuacion', models.DateField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('imagen_valoracion', models.ImageField(blank=True, null=True, upload_to='valoraciones/')),
                ('id_producto', models.ForeignKey(db_column='id_producto', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='tienda.producto')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.CASCADE, related_name='valoraciones', to='tienda.usuario')),
            ],
            options={
                'db_table': 'valoraciones',
                'ordering': ['-fecha_puntuacion'],
                'managed': True,
            },
        ),
    ]
