# Generated by Django 6.0.3 on 2026-04-02 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0008_producto_imagen_valoracion'),
    ]

    operations = [
    ]
