# Generated by Django 6.0.3 on 2026-04-15 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0009_auto_20260402_0839'),
    ]

    operations = [
        migrations.AddField(
            model_name='personalizacion',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('en_proceso', 'En proceso'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado'), ('cancelado_cliente', 'Cancelado por el cliente'), ('terminado', 'Terminado')], default='pendiente', max_length=20),
        ),
    ]
